/* NorthStar Books - ICT923 Part B functional demo. Fictional sample data only.
   The demo stores records in localStorage; it is NOT a secured multi-user CRM. */
"use strict";
const KEY="northstar-ict923-demo-v2";
const REWARDS=[{id:"voucher5",name:"$5 Book Voucher",cost:500,detail:"Demo voucher for a future purchase."},{id:"shipping",name:"Free Shipping",cost:750,detail:"Demo shipping benefit."},{id:"voucher10",name:"$10 Book Voucher",cost:1000,detail:"Demo voucher for a future purchase."}];
const seed=()=>({nextId:3,customers:[{id:"NS001",name:"Emily Carter",email:"emily@example.test",phone:"",points:650,lifetimePoints:650,purchases:0},{id:"NS002",name:"James Wilson",email:"james@example.test",phone:"",points:150,lifetimePoints:150,purchases:0}],purchases:[],redemptions:[],events:[]});
function readState(){try{const raw=localStorage.getItem(KEY);if(!raw)return seed();const parsed=JSON.parse(raw);if(!Array.isArray(parsed.customers)||!Array.isArray(parsed.events)||!Array.isArray(parsed.purchases)||!Array.isArray(parsed.redemptions)||!Number.isInteger(parsed.nextId))throw Error("Invalid demo state");return parsed}catch(e){return seed()}}
let state=readState();
const el=id=>document.getElementById(id),money=n=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(n),fmt=n=>n.toLocaleString("en-AU");
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch(e){notice("Local storage unavailable. Changes may not survive refresh.","error");return false}}
function notice(message,kind="success"){const node=el("alert");node.textContent=message;node.className="notice"+(kind==="error"?" error":"")}
function tier(p){return p>=3000?"Platinum":p>=1500?"Gold":p>=500?"Silver":"Bronze"}
function getCustomer(id){return state.customers.find(c=>c.id===id)}
function addEvent(type,detail){state.events.unshift({type,detail,at:new Date().toISOString()})}
function cell(tr,value){const td=document.createElement("td");td.textContent=value;tr.append(td);return td}
function renderTable(){const tbody=el("customer-rows");tbody.replaceChildren();const q=el("customer-search").value.toLowerCase().trim();const list=state.customers.filter(c=>[c.id,c.name,c.email].some(v=>v.toLowerCase().includes(q)));for(const c of list){const row=document.createElement("tr");cell(row,c.id+" · "+c.name);cell(row,c.email);cell(row,tier(c.lifetimePoints));cell(row,fmt(c.points));cell(row,String(c.purchases));tbody.append(row)}if(!list.length){const tr=document.createElement("tr");const td=cell(tr,"No matching customers");td.colSpan=5;tbody.append(tr)}}
function renderSelect(id,selected){const select=el(id);select.replaceChildren();for(const c of state.customers){const option=document.createElement("option");option.value=c.id;option.textContent=c.name+" ("+c.id+")";select.append(option)}if(getCustomer(selected))select.value=selected}
function activityView(node,events){node.replaceChildren();if(!events.length){const p=document.createElement("p");p.className="muted";p.textContent="No activity yet. Record a purchase to begin.";node.append(p);return}for(const e of events){const div=document.createElement("div");div.className="activity";const span=document.createElement("span");span.textContent=e.detail;const when=document.createElement("small");when.textContent=new Date(e.at).toLocaleString("en-AU");div.append(span,when);node.append(div)}}
function render(){el("metric-customers").textContent=fmt(state.customers.length);el("metric-points").textContent=fmt(state.customers.reduce((s,c)=>s+c.points,0));el("metric-sales").textContent=money(state.purchases.reduce((s,p)=>s+p.amountCents,0)/100);el("metric-rewards").textContent=fmt(state.redemptions.length);const tiers=el("tier-summary");tiers.replaceChildren();for(const name of ["Bronze","Silver","Gold","Platinum"]){const d=document.createElement("div");d.className="tier";const n=document.createElement("span");n.textContent=name;const count=document.createElement("strong");count.textContent=String(state.customers.filter(c=>tier(c.lifetimePoints)===name).length);d.append(n,count);tiers.append(d)}activityView(el("recent-activity"),state.events.slice(0,5));activityView(el("full-activity"),state.events);renderTable();const p=el("purchase-customer").value,r=el("reward-customer").value;renderSelect("purchase-customer",p);renderSelect("reward-customer",r);renderPurchases();renderRewards()}
function renderPurchases(){const node=el("purchase-history");node.replaceChildren();if(!state.purchases.length){node.textContent="No purchases recorded yet.";node.className="muted";return}node.className="";for(const p of state.purchases.slice(0,12)){const d=document.createElement("div");d.className="activity";const a=document.createElement("span");a.textContent=p.book+" · "+(getCustomer(p.customerId)?.name||p.customerId);const b=document.createElement("small");b.textContent=money(p.amountCents/100)+" · +"+p.points+" pts";d.append(a,b);node.append(d)}}
function renderRewards(){const c=getCustomer(el("reward-customer").value);el("available-points").textContent=c?fmt(c.points)+" available points":"No customer selected";const grid=el("reward-grid");grid.replaceChildren();for(const reward of REWARDS){const card=document.createElement("article");card.className="reward-card";const title=document.createElement("h3");title.textContent=reward.name;const desc=document.createElement("p");desc.textContent=reward.detail;const price=document.createElement("strong");price.textContent=fmt(reward.cost)+" points";const btn=document.createElement("button");btn.className="button";btn.textContent="Redeem reward";btn.disabled=!c||c.points<reward.cost;btn.addEventListener("click",()=>redeem(c.id,reward.id));card.append(title,desc,price,btn);grid.append(card)}}
function addCustomer(event){event.preventDefault();const name=el("new-name").value.trim(),email=el("new-email").value.trim().toLowerCase(),phone=el("new-phone").value.trim();if(!name||!el("new-email").checkValidity()){notice("Enter a valid name and email.","error");return}if(state.customers.some(c=>c.email.toLowerCase()===email)){notice("A customer with that email already exists.","error");return}const customer={id:"NS"+String(state.nextId++).padStart(3,"0"),name,email,phone,points:0,lifetimePoints:0,purchases:0};state.customers.push(customer);addEvent("customer","Customer created: "+customer.name);save();render();el("customer-form").reset();el("customer-dialog").close();notice("Customer "+customer.id+" registered.")}
function purchase(event){event.preventDefault();const c=getCustomer(el("purchase-customer").value),book=el("purchase-book").value.trim(),amount=Number(el("purchase-amount").value);if(!c||!book||!Number.isFinite(amount)||amount<=0||amount>100000){notice("Choose a customer, book and valid amount (up to AUD 100,000).","error");return}const cents=Math.round(amount*100);if(cents<1){notice("Minimum purchase is AUD 0.01.","error");return}const points=Math.floor(cents/100);c.points+=points;c.lifetimePoints+=points;c.purchases++;const p={id:"TX"+String(state.purchases.length+1).padStart(4,"0"),customerId:c.id,book,amountCents:cents,points,at:new Date().toISOString()};state.purchases.unshift(p);addEvent("purchase",c.name+": "+book+" · "+money(cents/100)+" · +"+points+" points");save();render();el("purchase-book").value="";el("purchase-amount").value="";notice("Purchase "+p.id+" recorded. "+points+" points awarded automatically.")}
function redeem(customerId,rewardId){const c=getCustomer(customerId),reward=REWARDS.find(r=>r.id===rewardId);if(!c||!reward)return;if(c.points<reward.cost){notice("Insufficient points for this reward.","error");render();return}if(!confirm("Redeem "+reward.name+" for "+fmt(reward.cost)+" points from "+c.name+"?"))return;c.points-=reward.cost;const tx={id:"RD"+String(state.redemptions.length+1).padStart(4,"0"),customerId:c.id,rewardId:reward.id,cost:reward.cost,at:new Date().toISOString()};state.redemptions.unshift(tx);addEvent("redemption",c.name+": redeemed "+reward.name+" · -"+reward.cost+" points");save();render();notice("Redemption "+tx.id+" completed; points deducted.")}
document.querySelectorAll(".nav").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.page)));document.querySelectorAll("[data-goto]").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.goto)));
function showPage(page){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===page));document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===page));el("page-title").textContent=({dashboard:"Overview",customers:"Customers",purchases:"Purchases",rewards:"Rewards",activity:"Activity log"})[page]||"Overview";el("alert").textContent="";el("alert").className=""}
el("customer-form").addEventListener("submit",addCustomer);el("purchase-form").addEventListener("submit",purchase);el("customer-search").addEventListener("input",renderTable);el("reward-customer").addEventListener("change",renderRewards);el("new-customer").addEventListener("click",()=>el("customer-dialog").showModal());el("close-dialog").addEventListener("click",()=>el("customer-dialog").close());el("reset-demo").addEventListener("click",()=>{if(!confirm("Reset all demonstration records in this browser?"))return;state=seed();save();render();notice("Demo records reset.")});
render();